name: release

on:
  workflow_dispatch:

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"

      - name: Build files
        run: ./build.sh github.com/eitamonya/cligpt

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.tag_version.outputs.new_tag }}
          title: Release ${{ steps.tag_version.outputs.new_tag }}
          files: ./dist/*
